version: '1.0'

services:
  database:
    image: postgres:14-alpine
    container_name: ctr_xss_injection_postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_db_xss:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres

volumes: # enable persistence of database data across container restart
  postgres_db_xss:
    driver: local